config/routes.rb
Rails.application.routes.draw do

  
  

  root :to => "consoles#index"

  resources :consoles do
     collection do
      get :login
      post :fblogin
      post :googlelogin
      post :signin
      get :index_old
      get :index_new
      get :abc
      get :logout
      get :aboutus
      get :test
      get :subscription
      get :templateindex
      get :testtemplate
      get :notice
    end
  end
  resources :accounts do
     collection do
      get :register
      get :fbregister
      get :googleregister
      get :login
      get :console_edit
      post :signin
      get :logout
      get :test
      get :myaccount
    end
  end
  resources :account_levels do
    collection do
    end
  end
  resources :specialoffers do
    collection do
      get :select_product
      post :insertproduct
      get :index_old
      post :add_to_salecart
    end
  end
  resources :newsboards do
    collection do
    end
  end
  resources :newsletters do
    collection do
    end
  end
    resources :orders do
     collection do
      get :usercheckpay
      get :orderdetail
      get :confirmpay
      get :confirmdelivery
      get :takeproduct
      get :orderdone
      post :usercheckpay_update
      get :checkorder

    end
  end
  resources :brands do
     collection do
    end
  end

  resources :products do
    collection do
      get :console_index
      get :list
      get :progressbar
      get :outofstock
      get :del_register
      get :copy
      post :add_to_shoppingcart
      get :shoppingcart
      get :shoppingcart_del
      get :shoppingcart_plus
      get :shoppingcart_minus
      get :sellcart_del
      get :newlist
      get :products_template
      get :shopprocess
      get :register
      get :edit_productname
      get :edit_option_surplus
      get :edit_option_price
      get :edit_option_name
      post :product_register
      post :upload_images_del
      post :option_del
    end
  end
    resources :type_ones do
    collection do
      get :type_two_get
      get :type_three_get
      get :progressbar
      post :type_two_del
      post :type_three_del
    end
  end
  resources :deliveries do
    collection do
      get :progressbar
      get :index_old
    end
  end
  resources :payments do
    collection do
      get :progressbar
    end
  end
  resources :messages do
    collection do
      get :product_message
      get :order_message
      get :progressbar
      post :reply
    end
  end
  resources :product_messages do
    collection do
      post :reply
    end
  end
  resources :order_messages do
    collection do
      post :reply
      get :read
    end
  end
    resources :system_settings do
     collection do
    end
  end
    resources :hcolors do
     collection do
      get :zhongxiao
    end
  end
  resources :bets do
     collection do
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
	has_many :replies, :dependent => :destroy
	belongs_to :account, foreign_key: "account_id"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_filter :current_user
before_filter :setting
before_action :set_message, only: [:edit, :update, :destroy,:show]
  def index
      if params[:order].present?
        if @current_user.role == 1
          @messages = OrderMessage.all
          @messages = @messages.like(params[:filter]) if params[:filter]
          @messages = @messages.order(updated_at: :desc)
          @messages_size = @messages.size
          @messages = @messages.page(params[:page]).per(15)
        else
          @messages = @current_user.order_messages
          @messages = @messages.like(params[:filter]) if params[:filter]
          @messages = @messages.order(updated_at: :desc)
          @messages_size = @messages.size
          @messages = @messages.page(params[:page]).per(15)
        end
      elsif params[:product].present?
        if @current_user.role == 1
          @messages = ProductMessage.all
          @messages = @messages.like(params[:filter]) if params[:filter]
          @messages = @messages.order(updated_at: :desc)
          @messages_size = @messages.size
          @messages = @messages.page(params[:page]).per(15)
        else
          @messages = @current_user.product_messages
          @messages = @messages.like(params[:filter]) if params[:filter]
          @messages = @messages.order(updated_at: :desc)
          @messages_size = @messages.size
          @messages = @messages.page(params[:page]).per(15)
        end
      else
        if @current_user.role == 1
          @messages = Message.all
          @messages = @messages.like(params[:filter]) if params[:filter]
          @messages = @messages.order(updated_at: :desc)
          @messages_size = @messages.size
          @messages = @messages.page(params[:page]).per(15)
        else
          @messages = @current_user.messages
          @messages = @messages.like(params[:filter]) if params[:filter]
          @messages = @messages.order(updated_at: :desc)
          @messages_size = @messages.size
          @messages = @messages.page(params[:page]).per(15)
        end
      end



  end
def new
    @message = Message.new
  
  end

  def create
    @message = Message.new(message_params)
    @message.account_id = @current_user.id
    @message.account_name = @current_user.name
    if @message.save
      content = "使用者 "+@current_user.name.to_s+" 在留言板留下了新留言。<br>主旨："+@message.title.to_s+"<br>內容："+@message.content+"<br>請登入後台回覆留言。"
      NewsMailer.system_email("新留言通知",content).deliver_now!
    	render :text => "success"
	else
		render :text => "error"
	end
  end

  def edit
    render :layout => false
  end

  def update
    if @message.update(message_params)
      render :text => "success"
    else
      render :text => "error"
    end
  end
  def show
    @reply = Reply.new
  render :layout => false
  end
  def product_message
  @message = ProductMessage.find(params[:id])
  render :layout => false
  end
  def order_message
  @message = OrderMessage.find(params[:id])
  render :layout => false
  end
  def destroy
    @message.destroy

    redirect_to messages_path
  end
  def reply
    @reply = Reply.new
    @message = Message.find(params[:message_id])
    @reply.message_id = params[:message_id]
    @reply.account_id = @current_user.id
    @reply.account_name = @current_user.name
    @reply.content = params[:replycontent]
    if @current_user.role == 1
      @message.update(status: 1)
    else
      @message.update(status: 0)
    end
    if @reply.save
      content_to_user = "您的留言「"+@message.content.to_s+"」有了新回覆。"
      NewsMailer.normal_email("留言回覆通知",content_to_user,@message.account_id).deliver_now!
      render :text => "success"
    else
      render :text => "error"
    end
  end

    def message_params
    params.require(:message).permit(:title, :content)
  end
    def set_message
    @message = Message.find(params[:id])
  end
end

app/views/messages/_messages.html.erb
  <h3 class="ui center aligned icon header" style="font-size:20px;margin:10px 0 10px 0;">
    <div class="content">一般留言</div>
  </h3>
<div class="infinite-table">
  <table id="payments_table" class="site-font ui sortable selectable teal table">
    <thead>
      <tr>
        <th>編號</th>
        <th>使用者名稱</th>
        <th>主旨</th>
        <th>日期</th>
        <th>是否回覆</th>
        <th style="margin: 0 10px 0 10px;">功能</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
      <tr>
        <td><%= message.id%></td>
        <td><%= message.account_name %></td>
        <td><%= message.title%></td>
        <td><%= message.created_at.strftime("%Y-%m-%d") %></td>
        <td>
        <% if message.status == 1 %>
          已回覆
        <% else %>
          未回覆
        <% end %>
        </td>
 
        <td class="collapsing">
          <button class="ui brown basic button message_content" data-value="<%= message.id %>">回覆</button>
          <%= link_to message, class: 'ui orange basic button message_del', method: :delete, data:{id: message.id} do %>
            刪除
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <p class="pagination">
    <%= link_to_next_page @messages, 'Next Page', :params => {:filter => @search_param}%>
  </p>
</div>

app/views/messages/_order_messages.html.erb
  <h3 class="ui center aligned icon header" style="font-size:20px;margin:10px 0 10px 0;">
    <div class="content">訂單留言</div>
  </h3>
<div class="infinite-table">
  <table id="payments_table" class="site-font ui sortable selectable teal table">
    <thead>
      <tr>
        <th>編號</th>
        <th>訂單編號</th>
        <th>使用者名稱</th>
        <th>日期</th>
        <th>是否回覆</th>
        <th style="margin: 0 10px 0 10px;">功能</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
      <tr>
        <td><%= message.id%></td>
        <td><%= message.order.ordernumber%></td>
        <td><%= message.account_name %></td>
        <td><%= message.created_at.strftime("%Y-%m-%d") %></td>
        <td>
        <% if message.status == 1 %>
        
          已回覆

        <% else %>

          未回覆

        <% end %>
        </td>
 
        <td class="collapsing">
          <button class="ui brown basic button order_message_content" data-value="<%= message.id %>">回覆</button>
          <%= link_to message, class: 'ui orange basic button message_del', method: :delete, data:{id: message.id} do %>
            刪除
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <p class="pagination">
    <%= link_to_next_page @messages, 'Next Page', :params => {:filter => @search_param}%>
  </p>
</div>

app/views/messages/_product_messages.html.erb
  <h3 class="ui center aligned icon header" style="font-size:20px;margin:10px 0 10px 0;">
    <div class="content">商品留言</div>
  </h3>
<div class="infinite-table">
  <table id="payments_table" class="site-font ui sortable selectable teal table">
    <thead>
      <tr>
        <th>編號</th>
        <th>商品名稱</th>
        <th>使用者名稱</th>
        <th>日期</th>
        <th>是否回覆</th>
        <th style="margin: 0 10px 0 10px;">功能</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
      <tr>
        <td><%= message.id%></td>
        <td><%= message.product.name%></td>
        <td><%= message.account_name %></td>
        <td><%= message.created_at.strftime("%Y-%m-%d") %></td>
        <td>
        <% if message.status == 1 %>
          已回覆

        <% else %>

          未回覆

        <% end %>
        </td>
 
        <td class="collapsing">
          <button class="ui brown basic button product_message_content" data-value="<%= message.id %>">回覆</button>
          <%= link_to message, class: 'ui orange basic button message_del', method: :delete, data:{id: message.id} do %>
            刪除
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <p class="pagination">
    <%= link_to_next_page @messages, 'Next Page', :params => {:filter => @search_param}%>
  </p>
</div>

app/views/messages/index.html.erb
<div class="global-wrapper clearfix" id="global-wrapper">
        <%= render "common/theboxheader" %>

<div class="container">
            <header class="page-header" style="padding:0">

            </header>
           <div class="row row-col-border" data-gutter="60">
                <div class="col-md-3">
  					<ul class="nav nav-list">
  					<div class="ui center aligned icon header" style="font-size:18px;margin:20px 0 22px 0;">
  					<li> 留言總數： <%= number_with_delimiter(@messages_size, :delimiter => ',') %></li>
  					<li><br></li>
    				<li><a style="color:black;" href="/messages">一般留言</a></li>
    				<li><a style="color:black;" href="/messages?product=1">商品留言</a></li>
    				<li><a style="color:black;" href="/messages?order=1">訂單留言</a></li>
    				</div>
  					</ul>
                </div>
                <div class="col-md-9">
    				<h1 class="ui center aligned icon header" style="font-size:28px;margin:20px 0 16px 0;">
    				<div class="content">留言管理</div>
  					</h1>
  					<div class="ui horizontal divider">Messages</div>

    				<% if @messages.present? %>
      					<% if @messages.size != 0 %>
        					<% if params[:order].present? %>
        						<%= render :partial => 'order_messages', :object => @messages %>
        					<%elsif params[:product].present? %>
        						<%= render :partial => 'product_messages', :object => @messages %>
        					<% else %>
          						<%= render :partial => 'messages', :object => @messages %>
        					<% end %>       
      					<% else %>
        					<h3>未建立！</h3>
      					<% end %>
    				<% end %>

				  </div>

			</div>
</div>


  <div class="gap"></div>
    <%= render "common/footerbar" %>
</div>
<div class="ui small modal edit-account" style="padding-top:0px;">
  <i class="close icon"></i>
  <div id="edit_from" style="padding:10px;">
  </div>
</div>

<div class="ui basic modal delete-check">
  <i class="close icon"></i>
  <div class="header">
    刪除留言 <span class="primary-orange target_message"></span>
  </div>
  <div class="image content">
    <div class="image">
      <i class="announcement icon"></i>
    </div>
    <div class="description">
      <p>確定要刪除留言<span class="primary-orange target_message"></span>嗎?</p>
    </div>
  </div>
  <div class="actions">
    <div class="two fluid ui inverted buttons">
      <div class="ui ok red basic inverted button">
        <i class="remove icon"></i>
        刪除
      </div>
      <div class="ui cancel blue basic inverted button">
        <i class="checkmark icon"></i>
        取消
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(function(){

  $('#messages_table').tablesort();

  $('body').on('click','.message_edit',function(){
    $('.ui.dimmer.main').dimmer('show');

    var row_id = $(this).data("value");
    $.get( "/messages/"+row_id+"/edit", function(html) {
      $("#edit_from").empty();
      $("#edit_from").append(html);
      $('.ui.dimmer.main').dimmer('hide');

      $('.ui.modal.edit-account').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
  });

  $('body').on('click', '.message_del',function(){
    var href = this.href;
    var orign_link = $(this);
    var message_id = $(this).data("id");
    console.log(message_id);

    $(".target_message").text(message_id);

    $('.delete-check').modal({
        onApprove : function() {
          $.ajax({
            type: "get",
            method: "delete",
            url: href
          });
          $('.ui.dimmer.main').dimmer('show');
          location.reload();
        }
      }).modal('refresh').modal('show');

    return false;
  });


  $('body').on('click','.message_content',function(){
    $('.ui.dimmer.main').dimmer('show');

    var row_id = $(this).data("value");
    $.get( "/messages/"+row_id, function(html) {
      $("#edit_from").empty();
      $("#edit_from").append(html);
      $('.ui.dimmer.main').dimmer('hide');

      $('.ui.modal.edit-account').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
  });
  $('body').on('click','.order_message_content',function(){
    $('.ui.dimmer.main').dimmer('show');

    var row_id = $(this).data("value");
    $.get( "/messages/order_message?id="+row_id, function(html) {
      $("#edit_from").empty();
      $("#edit_from").append(html);
      $('.ui.dimmer.main').dimmer('hide');

      $('.ui.modal.edit-account').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
  });
  $('body').on('click','.product_message_content',function(){
    $('.ui.dimmer.main').dimmer('show');

    var row_id = $(this).data("value");
    $.get( "/messages/product_message?id="+row_id, function(html) {
      $("#edit_from").empty();
      $("#edit_from").append(html);
      $('.ui.dimmer.main').dimmer('hide');

      $('.ui.modal.edit-account').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
  });
  //   $('body').on('click','.reply-btn',function(){
  //     alert("dd");
  //   $.ajax({
  //       url: $(this).attr('action'), //sumbits it to the given url of the form
  //       type: 'POST',
  //       processData: false,
  //       contentType: false,
  //       data: new FormData(this)
  //   }).success(function(upload_result){
  //       console.log(upload_result);
  //       if(upload_result == "success" ){
  //         $("#edit_from").empty();
  //         $("#edit_from").append(html);
  //         $('.ui.dimmer.main').dimmer('hide');

  //         $('.ui.modal.edit-account').modal({
  //           observeChanges: true
  //     }).modal('refresh').modal('show');
  //       }
  //   }).fail(function(e) {
  //     $('.ui.dimmer.main').dimmer('hide');
  //       console.log(e);
  //   }).done(function(){
      
  //   });
  //   return false; // prevents normal behaviour
  // });


});
</script>

app/views/messages/new.html.erb
<div class="global-wrapper clearfix" id="global-wrapper">
        <%= render "common/theboxheader" %>

<div class="container">

<h1 class="ui center aligned icon header" style="font-size:28px;margin:20px 0 22px 0;">
 
    <div class="content">
      留言版
    </div>
  </h1>
  <%= form_for(@message) do |f| %>
  <div class="ui stackable one column centered grid">
    <div class="fourteen wide column">
      <div class="ui large form" style="text-align:left;">
      <div class="required field">
        <label>主旨 Title：</label>
        <%= f.text_field :title, placeholder: "請輸入主旨" %>
      </div>
      <div class="required field">
        <label>內容 Content：</label>
        <%= f.text_area :content, placeholder: "請輸入內容" %>
      </div>
      </div>
    <br>
    <div class="ui divider"></div>
    <% if @current_user.present? && @current_user.role == 2 %>
    <button id="message_form_submit" class="ui teal basic button">
      <i class="write icon"></i>送出
    </button>
    <% else %>
    <h1 class="ui center aligned icon header">
    <a class="ui red button" style="text-align:center;"  href="/consoles/login">請先登入會員</a>
    </h1>
    <% end %>
    </div>
    </div>
    <% end %>


</div>


  <div class="gap"></div>
    <%= render "common/footerbar" %>
</div>

 <script type="text/javascript">
$(function(){

  $('form').submit(function() {
    var valuesToSubmit = $(this).serialize();
    $("#to_message").addClass("loading");
    console.log($(this).attr('action'));
    $.ajax({
        url: $(this).attr('action'), //sumbits it to the given url of the form
        type: 'POST',
        processData: false,
        contentType: false,
        data: new FormData(this)
    }).success(function(upload_result){
        console.log(upload_result);
        if(upload_result == "success" ){
          window.location.replace("http://"+location.host+"/messages/");
        }
    }).fail(function(e) {
        console.log(e);
    }).done(function(){
      $("#to_message").removeClass("loading");
    });
    return false; // prevents normal behaviour
  });
});

</script>

 <style type="text/css">
.box1{                           
 position:absolute;    
 bottom: 0px;              
}
.box2{                            
 height: 480px;               
 position: relative;
}
</style>

app/views/messages/new_old.html.erb
<div class="ui container">
  <h1 class="ui center aligned icon header" style="font-size:28px;margin:20px 0 22px 0;">
 
    <div class="content">
      留言版
    </div>
  </h1>
<div class="ui horizontal divider">Message</div>

<%= form_for(@message) do |f| %>
<div class="ui stackable one column centered grid">
  <div class="fourteen wide column">
    <div class="ui large form" style="text-align:left;">
      
      <div class="required field">
        <label>主旨 Title：</label>
        <%= f.text_field :title, placeholder: "請輸入主旨" %>
      </div>
      <div class="required field">
        <label>內容 Content：</label>
        <%= f.text_area :content, placeholder: "請輸入內容" %>
      </div>
    </div>
    <br>
    <div>

    <div class="ui divider"></div>
    <% if @current_user.present? && @current_user.role == 2 %>
    <button id="message_form_submit" class="ui teal basic button">
      <i class="write icon"></i>送出
    </button>
    <% else %>
    <div class="ui grey inverted stacked segment" style="text-align:center;">
  <label >請先登入會員</label>
</div>
    <% end %>

  </div>
</div>



<% end %>
<script type="text/javascript">
$(function(){
  $('select.dropdown')
    .dropdown()
  ;
  $('form').submit(function() {
    var valuesToSubmit = $(this).serialize();
    $("#to_message").addClass("loading");
    console.log($(this).attr('action'));
    $.ajax({
        url: $(this).attr('action'), //sumbits it to the given url of the form
        type: 'POST',
        processData: false,
        contentType: false,
        data: new FormData(this)
    }).success(function(upload_result){
        console.log(upload_result);
        if(upload_result == "success" ){
          window.location.replace("http://"+location.host+"/messages/");
        }
    }).fail(function(e) {
        console.log(e);
    }).done(function(){
      $("#to_message").removeClass("loading");
    });
    return false; // prevents normal behaviour
  });
});

function ValidateNumber(e, pnumber)
{
    if (!/^\d+$/.test(pnumber))
    {
        $(e).val(/^\d+/.exec($(e).val()));
    }
    return false;
}


</script>

app/views/messages/order_message.html.erb
<div class="ui comments">
  <div class="comment">
    <a class="avatar">
      <div class="image">
      <i class="user icon"></i>
    </div>
    </a>
    <div class="content">
      <a class="author"><%=@message.account_name%></a>
      <div class="metadata">
        <div class="date"><%= @message.created_at.strftime("%Y-%m-%d") %></div>
      </div>
      <div class="text">
        <%= @message.content %>
      </div>
    </div>
  </div>
  <% if @message.reply != nil %>
  <div class="comment">

    <a class="avatar">
      <div class="image">
      <i class="red user icon"></i>
      </div>
    </a>
    <div class="content">
      <a class="author">管理員</a>
      <div class="metadata">
        <div class="date"><%= @message.updated_at.strftime("%Y-%m-%d") %></div>
      </div>
      <div class="text">
        <%= @message.reply %>
      </div>
    </div>
  </div>
  <% end %>
<div class="form-check">
  <%= form_for @message ,:html =>{:class => "ui reply form"}, :url => reply_order_messages_path, method: :post do |f| %>
      <input type="hidden" id="message_id" name="message_id" value="<%=@message.id%>">
    <div class="field">
      <textarea id="replycontent" name = "replycontent" rows="3"></textarea>
    </div>
    <div id="reply-btn" class="ui primary labeled icon button reply-btn">
      <i class="icon edit"></i> 回覆
    </div>
<% end %>
</div>
</div>
<script type="text/javascript">
  $('.form-check form').on('click','.reply-btn',function(){

    var message_id = document.getElementById("message_id").value;
    var replycontent = document.getElementById("replycontent").value;
    var request = "/order_messages/reply";

      var aj = $.ajax({
          url: request,
          type: 'post',
          data:{
             message_id: message_id,
             replycontent: replycontent
           },
          dataType: 'json'
        }).success(function(upload_result) {
          if(upload_result == "success" ){
            window.location.replace("/"+location.host+"/messages");
          }
        }).fail(function(data) {
       $.get( "/messages/order_messages?id="+message_id, function(html) {
          $("#edit_from").empty();
          $("#edit_from").append(html);
          $('.ui.dimmer.main').dimmer('hide');

          $('.ui.modal.edit-order').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
        });
    return false; // prevents normal behaviour
  });
  </script>

app/views/messages/product_message.html.erb
<div class="ui comments">
  <div class="comment">
    <a class="avatar">
      <div class="image">
      <i class="user icon"></i>
    </div>
    </a>
    <div class="content">
      <a class="author"><%=@message.account_name%></a>
      <div class="metadata">
        <div class="date"><%= @message.created_at.strftime("%Y-%m-%d") %></div>
      </div>
      <div class="text">
        <%= @message.content %>
      </div>
    </div>
  </div>
  <% if @message.reply != nil %>
  <div class="comment">

    <a class="avatar">
      <div class="image">
      <i class="red user icon"></i>
    </div>
    </a>
    <div class="content">
      <a class="author">管理員</a>
      <div class="metadata">
        <div class="date"><%= @message.updated_at.strftime("%Y-%m-%d") %></div>
      </div>
      <div class="text">
        <%= @message.reply %>
      </div>
    </div>
  </div>
  <% end %>
<div class="form-check">
  <%= form_for @message ,:html =>{:class => "ui reply form"}, :url => reply_product_messages_path, method: :post do |f| %>
      <input type="hidden" id="message_id" name="message_id" value="<%=@message.id%>">
    <div class="field">
      <textarea id="replycontent" name = "replycontent" rows ="3"></textarea>
    </div>
    <div id="reply-btn" class="ui primary labeled icon button reply-btn">
      <i class="icon edit"></i> 回覆
    </div>
<% end %>
</div>
</div>
<script type="text/javascript">
  $('.form-check form').on('click','.reply-btn',function(){

    var message_id = document.getElementById("message_id").value;
    var replycontent = document.getElementById("replycontent").value;
    var request = "/product_messages/reply";

      var aj = $.ajax({
          url: request,
          type: 'post',
          data:{
             message_id: message_id,
             replycontent: replycontent
           },
          dataType: 'json'
        }).success(function(upload_result) {
          if(upload_result == "success" ){
            window.location.replace("/"+location.host+"/messages");
          }
        }).fail(function(data) {
       $.get( "/messages/product_message?id="+message_id, function(html) {
          $("#edit_from").empty();
          $("#edit_from").append(html);
          $('.ui.dimmer.main').dimmer('hide');

          $('.ui.modal.edit-order').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
        });
    return false; // prevents normal behaviour
  });
  </script>

app/views/messages/show.html.erb
<div class="ui comments">
  <div class="comment">
    <a class="avatar">
      <div class="image">
      <i class="user icon"></i>
    </div>
    </a>
    <div class="content">
      <a class="author"><%=@message.account_name%></a>
      <div class="metadata">
        <div class="date"><%= @message.created_at.strftime("%Y-%m-%d") %></div>
      </div>
      <div class="text">
      <h3><font color="blue"> <%= @message.title %></font></h3>
        <%= @message.content %>
      </div>
    </div>
  </div>
  <% if @message.replies.size > 0 %>
  <div class="comment">
    <% @message.replies.each do |r| %>
    <a class="avatar">
      <div class="image">
      <%if r.account.role == 1 %>
      <i class="red user icon"></i>
      <%else%>
      <i class="blue user icon"></i>
      <%end%>
    </div>
    </a>
    <div class="content">
      <a class="author"><%if r.account.role == 1 %>管理員<%= r.account_name %><%else%><%= r.account_name %><%end%></a>
      <div class="metadata">
        <div class="date"><%= r.created_at.strftime("%Y-%m-%d") %></div>
      </div>
      <div class="text">
        <%= r.content %>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
<div class="form-check">
  <%= form_for @reply ,:html =>{:class => "ui reply form"}, :url => reply_messages_path, method: :post do |f| %>
      <input type="hidden" id="message_id" name="message_id" value="<%=@message.id%>">
    <div class="field">
      <textarea id="replycontent" name = "replycontent"></textarea>
    </div>
    <div id="reply-btn" class="ui primary labeled icon button reply-btn">
      <i class="icon edit"></i> 回覆
    </div>
<% end %>
</div>
</div>
<script type="text/javascript">
  $('.form-check form').on('click','.reply-btn',function(){

    var message_id = document.getElementById("message_id").value;
    var replycontent = document.getElementById("replycontent").value;
    var request = "/messages/reply";

      var aj = $.ajax({
          url: request,
          type: 'post',
          data:{
             message_id: message_id,
             replycontent: replycontent
           },
          dataType: 'json'
        }).success(function(upload_result) {
          if(upload_result == "success" ){
            window.location.replace("/"+location.host+"/messages");
          }
        }).fail(function(data) {
       $.get( "/messages/"+message_id, function(html) {
          $("#edit_from").empty();
          $("#edit_from").append(html);
          $('.ui.dimmer.main').dimmer('hide');

          $('.ui.modal.edit-order').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $('.ui.dimmer.main').dimmer('hide');
      alert( "error" );
    });
        });
    return false; // prevents normal behaviour
  });
  </script>