config/routes.rb
Rails.application.routes.draw do

  
  

  root :to => "consoles#index"

  resources :consoles do
     collection do
      get :login
      post :fblogin
      post :googlelogin
      post :signin
      get :index_old
      get :index_new
      get :abc
      get :logout
      get :aboutus
      get :test
      get :subscription
      get :templateindex
      get :testtemplate
      get :notice
    end
  end
  resources :accounts do
     collection do
      get :register
      get :fbregister
      get :googleregister
      get :login
      get :console_edit
      post :signin
      get :logout
      get :test
      get :myaccount
    end
  end
  resources :account_levels do
    collection do
    end
  end
  resources :specialoffers do
    collection do
      get :select_product
      post :insertproduct
      get :index_old
      post :add_to_salecart
    end
  end
  resources :newsboards do
    collection do
    end
  end
  resources :newsletters do
    collection do
    end
  end
    resources :orders do
     collection do
      get :usercheckpay
      get :orderdetail
      get :confirmpay
      get :confirmdelivery
      get :takeproduct
      get :orderdone
      post :usercheckpay_update
      get :checkorder

    end
  end
  resources :brands do
     collection do
    end
  end

  resources :products do
    collection do
      get :console_index
      get :list
      get :progressbar
      get :outofstock
      get :del_register
      get :copy
      post :add_to_shoppingcart
      get :shoppingcart
      get :shoppingcart_del
      get :shoppingcart_plus
      get :shoppingcart_minus
      get :sellcart_del
      get :newlist
      get :products_template
      get :shopprocess
      get :register
      get :edit_productname
      get :edit_option_surplus
      get :edit_option_price
      get :edit_option_name
      post :product_register
      post :upload_images_del
      post :option_del
    end
  end
    resources :type_ones do
    collection do
      get :type_two_get
      get :type_three_get
      get :progressbar
      post :type_two_del
      post :type_three_del
    end
  end
  resources :deliveries do
    collection do
      get :progressbar
      get :index_old
    end
  end
  resources :payments do
    collection do
      get :progressbar
    end
  end
  resources :messages do
    collection do
      get :product_message
      get :order_message
      get :progressbar
      post :reply
    end
  end
  resources :product_messages do
    collection do
      post :reply
    end
  end
  resources :order_messages do
    collection do
      post :reply
      get :read
    end
  end
    resources :system_settings do
     collection do
    end
  end
    resources :hcolors do
     collection do
      get :zhongxiao
    end
  end
  resources :bets do
     collection do
    end
  end

end

app/views/common/_accountleftmenu.html.erb
<div class="row pull-left">
<div id="sidebar" class="span3">

<div class="well well-small">
	<ul class="nav nav-list">
		<li><a href="/accounts/myaccount"><h4>・基本資料</h4></a></li>
		<li><a href="/orders"><h4>・我的訂單</h4></a></li>
		<li><a href="/products/shoppingcart"><h4>・購物車</h4></a></li>
		<li style="border:0"> &nbsp;</li>
		<% if @current_user.present? && @current_user.role!=1%>
		<li> <a class="totalInCart" href="/products/shoppingcart"><strong>購物車金額  <span class="badge badge-warning pull-right" style="line-height:18px;"><%if @catrprice.present? %>$<%=@cartprice%><%else%>沒有商品<%end%></span></strong></a></li>
		<%end%>
	</ul>
</div>

<div class="well well-small alert alert-info" >
  <h2 class= "cntr">最新消息</h2>
  <% if @newsboards.present? %>
  	<% @newsboards.each do |n| %>
  	<div id="<%= n.id %>">
   	<i class="browser icon"></i><a href="/newsboards/<%=n.id%>"><%= n.title %></a>
   	<font size="0.1" ><span class="float:right"><%= n.created_at.strftime("%Y-%m-%d") %></span></font>
    </div>
    </br>
    <%end%>
<%end%>
</div>
		<div class="well well-small alert alert-warning cntr">
			<h2>優惠活動</h2>
				  <p>多種促銷組合優惠！！ <br><br><a class="defaultBtn" href="/specialoffers">Click here </a></p>
		</div>
		<div class="well well-small alert alert-info cntr" >
  			<h2>訂閱電子報</h2>接收最新商品與優惠通知
  				<input id="newsletter_email" type="text" placeholder="Enter email"><br>
 				<a class="ui primary small button" id="subscription" height="2">訂閱</a>
		</div>
			<br>
			<br>
			<ul class="nav nav-list promowrapper">
			<li>
			  <div class="thumbnail">
				<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
				<img src="<%= asset_path 'bootstrap-ecommerce-templates.png' %>" alt="bootstrap ecommerce templates">
				<div class="caption">
				  <h4><a class="defaultBtn" href="product_details.html">VIEW</a> <span class="pull-right">$22.00</span></h4>
				</div>
			  </div>
			</li>
			<li style="border:0"> &nbsp;</li>
			<li>
			  <div class="thumbnail">
				<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
				<img src="<%= asset_path 'shopping-cart-template.png' %>" alt="shopping cart template">
				<div class="caption">
				  <h4><a class="defaultBtn" href="product_details.html">VIEW</a> <span class="pull-right">$22.00</span></h4>
				</div>
			  </div>
			</li>
		  </ul>

	</div>

app/views/common/_footerbar.html.erb
<footer class="main-footer">
        <div class="container">
            <div class="row row-col-gap" data-gutter="60">
                <div class="col-md-3">
                    <h4 class="widget-title-sm">Germanysky</h4>
                    <p>代購服務秉持的信念是   對客戶認真負責   價格要求平實不浮誇 
有跟過我們團的人都知道 
所以會介紹親朋好友一起來購買-- 大家能以平時的價格  買到德國的好物
沒有來過的  歡迎也來試試看喔</p>
                    <ul class="main-footer-social-list">
                        <li>
                            <a class="fa fa-facebook" href="#"></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h4 class="widget-title-sm">商品標籤</h4>
                    <ul class="main-footer-tag-list">
                        <li><a href="#">New Season</a>
                        </li>
                        <li><a href="#">Watches</a>
                        </li>
                        <li><a href="#">woman</a>
                        </li>
                        <li><a href="#">classic</a>
                        </li>
                        <li><a href="#">modern</a>
                        </li>
                        <li><a href="#">blue</a>
                        </li>
                        <li><a href="#">shoes</a>
                        </li>
                        <li><a href="#">running</a>
                        </li>
                        <li><a href="#">jeans</a>
                        </li>
                        <li><a href="#">sports</a>
                        </li>
                        <li><a href="#">laptops</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h4 class="widget-title-sm">電子報</h4>
                    <form>
                        <div class="form-group">
                            <label>輸入您的電子郵件以收到最新商品</label>
                            <input class="newsletter-input form-control" placeholder="Your e-mail address" type="text" />
                        </div>
                        <input class="btn btn-primary" type="submit" value="Sign up" />
                    </form>
                </div>
            </div>

        </div>
    </footer>
    <div class="copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p class="copyright-text">Copyright &copy; <a href="#">TheBox</a> 2014. Designed my remtsoy. All rights reseved</p>
                </div>
            </div>
        </div>
    </div>

app/views/common/_footerbar_old.html.erb
<section class="our_client">
	<hr class="soften"/>
	<h4 class="title cntr"><span class="text">友站連結</span></h4>
	<hr class="soften"/>
	<div class="row">
		<div class="span2">
			<a href="#"><img alt="" src="<%= asset_path '1.png' %>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%= asset_path '1.png' %>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%= asset_path '1.png' %>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%= asset_path '1.png' %>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%= asset_path '1.png' %>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%= asset_path '1.png' %>"></a>
		</div>
	</div>
</section>
<footer class="footer">
<div class="row-fluid">
<div class="span2">
<h5>帳戶中心</h5>
<a href="#">個人資料</a><br>
<a href="#">個人留言</a><br>
<a href="#">我的訂單</a><br>
<a href="#">購物車</a><br>
 </div>
<div class="span2">
<h5>相關資訊</h5>
<a href="#">關於我們</a><br>
<a href="#">聯繫我們</a><br>
<a href="#">注意事項</a><br>
 </div>
<div class="span2">
<h5>商品展示</h5>
<a href="#">最新商品</a> <br>
<a href="#">熱賣商品</a><br>
<a href="#">促銷活動</a><br>
 </div>
 <div class="span6">
<h5>關於我們</h5>
代購服務秉持的信念是   對客戶認真負責   價格要求平實不浮誇 
有跟過我們團的人都知道 
所以會介紹親朋好友一起來購買-- 大家能以平時的價格  買到德國的好物
沒有來過的  歡迎也來試試看喔
 </div>
 </div>
</footer>
</div><!-- /container -->

<div class="copyright">
<div class="container">
	<span>Copyright &copy; 2013<br> bootstrap ecommerce shopping template</span>
	<span>Copyright &copy; 2017<br> GermanySky OnlineShop</span>
</div>
</div>

app/views/common/_header.html.erb
<header id="header">
<div class="row">
	<div class="span4">
	<h1>
		<img src="<%= asset_path 'logo-bootstrap-shoping-cart.png' %>" alt="bootstrap sexy shop">
	</h1>
	</div>

          <div class="ui item pull-right" style="margin-top:35px; ">
              <input id="filter" type="text" placeholder="商品搜尋">
              <i id="search_go" class="search link icon"></i>
          </div>
</div>
</header>
<!--
Navigation Bar Section 
-->
<% if @current_user != nil && @current_user.role == 1 %>
<div class="main_menu_area">
      <ul id="nav">
        <li><a href="/">首頁</a></li>
        <li><a href="/newsboards">公佈欄設定</a></li>
        <li><a >商品管理</a>
          <ul>
            <li><a href="/products/console_index">商品管理</a></li>
            <li><a href="/products/outofstock">缺貨管理</a></li>
            <li><a href='/specialoffers'>促銷管理</a></li>
          </ul>
          </li>
        <li><a>分類與品牌</a>
          <ul>
            <li><a href="/type_ones">分類管理</a></li>
            <li><a href="/brands">品牌管理</a></li>
          </ul>
          </li>
        <li><a>付款與運送</a>
          <ul>
            <li><a href="/payments">付款管理</a></li>
            <li><a href="/deliveries">運送管理</a></li>
          </ul>
        </li>
        <li><a href="/orders">訂單管理</a></li>
        <li><a >使用者管理</a>
          <ul>
            <li><a href="/accounts">會員管理</a></li>
            <li><a href="/account_levels">等級管理</a></li>
            <li><a href="/messages">問答管理</a></li>
          </ul>
        </li>
        <li><a href="/newsletters">電子報發送</a></li>
        <li><a href="/system_settings">系統設定</a></li>
      </ul>
  </div>
<%else%>
<div class="main_menu_area">
      <ul id="nav">
        <li><a href="/">首頁</a></li>
        <li><a href="/newsboards">最新消息</a></li>
        <li><a href="/consoles/aboutus">關於我們</a></li>
        <li><a href="/specialoffers">促銷活動</a></li>
        <li><a href="/products">商品展示</a>
          <ul>
            <li><a href="#">===分類===</a></li>
            <% @type_ones.each do |t| %>
             <li><a href="/products?type=<%=t.id%>"><%=t.name %></a>
              <% if t.type_twos.size>0 %>
              <ul>
                <% t.type_twos.each do |two| %>
                <li><a href="/products?type2=<%=two.id%>"><%= two.name %></a></li>
                <% end %>
              </ul>
              <%end%>
            <% end %></li>
            <li><a href="#">===品牌===</a></li>
            <% @brands.each do |b| %>
            <li><a href="/products?brand=<%=b.id%>"><%=b.name %></a></li>
            <%end%>
          </ul>
        </li>
        <li><a href="/products/shopprocess">購物流程</a></li>
        <li><a href="/consoles/notice">注意事項</a></li>
        <li><a href="/messages/new">留言版</a></li>

      </ul>
  </div>
<%end%>
    <script type="text/javascript">

 $("#search_go").click(function(){
    start_search();
  });

  $(document).on('keypress', function(e) {
    if(e.which == 13) {
      start_search();
    }
  });

  function start_search(){
    var search_string = $("#filter").val();
    if(search_string == ""){
      search_msg.popup('toggle');
    }else{
      var target_url = "";
      if(window.location.href == "http://"+location.host+"/products"){
        target_url = window.location.href+"?filter="+search_string;
      }else if(window.location.href.indexOf('filter') > -1){
        target_url = "http://"+location.host+"/products?filter="+search_string;
      }else{
        target_url = "http://"+location.host+"/products?filter="+search_string;
      }
      window.location.replace(target_url);
    }
  }
 </script>

app/views/common/_leftmenu.html.erb
<div class="row pull-left">
<div id="sidebar" class="span3">

<div class="well well-small">

		<li><h4>分類</h4></li>
		<% @type_ones.each do |t| %>
		<li><a href="/products?type=<%=t.id%>" style="padding-left:50px;">．<%= t.name %></a></li>
		<% end %>
		<li><h4>品牌</h4></li>
		<% @brands.each do |b| %>
		<li><a href="/products?brand=<%=b.id%>" style="padding-left:50px;">．<%= b.name %></a></li>
		<% end %>
		
		<li style="border:0"> &nbsp;</li>
		<% if @current_user.present? && @current_user.role!=1%>
		<li> <a class="totalInCart" href="/products/shoppingcart"><strong>購物車金額  <span class="badge badge-warning pull-right" style="line-height:18px;"><%if @cartprice.present? %>$<%=@cartprice%><%else%>沒有商品<%end%></span></strong></a></li>
		<%end%>
	
</div>

<div class="well well-small alert alert-info" >
  <h2 class= "cntr">最新消息</h2>
  <% if @newsboards.present? %>
  	<% @newsboards.each do |n| %>
  	<div id="<%= n.id %>">
   	<i class="browser icon"></i><a href="/newsboards/<%=n.id%>"><%= n.title %></a>
   	<font size="0.1" ><span class="float:right"><%= n.created_at.strftime("%Y-%m-%d") %></span></font>
    </div>
    </br>
    <%end%>
<%end%>
</div>
		<div class="well well-small alert alert-warning cntr">
			<h2>優惠活動</h2>
				  <p>多種促銷組合優惠！！ <br><br><a class="defaultBtn" href="/specialoffers">Click here </a></p>
		</div>
		<div class="well well-small alert alert-info cntr" >
  			<h2>訂閱電子報</h2>接收最新商品與優惠通知
  				<input id="newsletter_email" type="text" placeholder="Enter email"><br>
 				<a class="ui primary small button" id="subscription" height="2">訂閱</a>
		</div>
			<br>
			<br>
			<ul class="nav nav-list promowrapper">
			<li>
			  <div class="thumbnail">
				<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span>前往商品</a>
				<img src="<%= asset_path 'a.jpg' %>" alt="germanysky shop">
				<div class="caption">
				  <h4><a class="defaultBtn" href="">VIEW</a> <span class="pull-right">$99</span></h4>
				</div>
			  </div>
			</li>
			<li style="border:0"> &nbsp;</li>
			<li>
			  <div class="thumbnail">
				<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span>前往商品</a>
				<img src="<%= asset_path 'a.jpg' %>" alt="germanysky shop">
				<div class="caption">
				  <h4><a class="defaultBtn" href="">VIEW</a> <span class="pull-right">$99</span></h4>
				</div>
			  </div>
			</li>
		  </ul>

	</div>

app/views/common/_leftsalebanner.html.erb
<div class="gap gap-small"></div>
    <div class="banner banner-o-hid" style="background-image:url(<%= asset_path '550x292.png' %>);">
        <a class="banner-link" href="#"></a>
        <div class="banner-caption-left">
            <h5 class="banner-title">夏日強打促銷優惠</h5>
            <p class="banner-desc">買三件以上一件199！</p>
            <p class="banner-shop-now">Shop Now <i class="fa fa-caret-right"></i>
            </p>
        </div>
        <img class="banner-img" src="<%= asset_path '21-i.png' %>" alt="Image Alternative text" title="Image Title" style="bottom: -29px; right: -51px; width: 120px;" />
    </div>

app/views/common/_navbar.html.erb
<% if @current_user != nil && @current_user.role == 1 %>
<div id="top_nav" class="ui top fixed large labeled icon menu grid" style="padding: 0 10px 0 10px;">
 <div class="grid menu row">
    <%= link_to consoles_path, class: "item" do %>
      <i class="home icon"></i>首頁
    <% end %>
    <%= link_to newsboards_path, class: "item" do %>
        <i class="user icon"></i>公佈欄設定
      <% end %>

      <div id="product_manage" class="ui icon dropdown item">
        <i class="clone icon"></i>
        商品管理
      </div>
      <div id="brand_menu" class="ui popup transition hidden">
        <div class="ui secondary vertical icon menu">
        <%= link_to console_index_products_path, class: "item" do %>
            <i class="in cart icon"></i>商品管理
        <% end %>
        <%= link_to outofstock_products_path, class: "item" do %>
            <i class="in cart icon"></i>缺貨管理
        <% end %>
        </div>
        </div>
    <div id="type_and_brand" class="ui icon dropdown item">
        <i class="clone icon"></i>
        分類與品牌
      </div>
      <div id="brand_menu" class="ui popup transition hidden">
        <div class="ui secondary vertical icon menu">
           <%= link_to type_ones_path, class: "item" do %>
      <i class="list layout icon"></i>分類管理
    <% end %>
      <%= link_to brands_path, class: "item" do %>
          <i class="bookmark icon"></i>品牌管理
    <% end %>
        </div>
        </div>
   <div id="pay_and_delivery" class="ui icon dropdown item" >
        <i class="clone icon"></i>
        付款與運送
      </div>
      <div id="pay_menu" class="ui popup transition hidden">
        <div class="ui secondary vertical icon menu">
            <%= link_to payments_path, class: "item" do %>
      <i class="calculator icon"></i>付款管理
    <% end %>
      <%= link_to deliveries_path, class: "item" do %>
        <i class="shipping icon"></i>運送管理
      <% end %>
        </div>
        </div>
   

      <%= link_to orders_path, class: "item" do %>
        <i class="sticky note icon"></i>訂單管理
      <% end %>

      <div id="user_manage" class="ui icon dropdown item" >
        <i class="clone icon"></i>
        使用者管理
      </div>
      <div id="account_menu" class="ui popup transition hidden">
        <div class="ui secondary vertical icon menu">
        <%= link_to accounts_path, class: "item" do %>
        <i class="user icon"></i>會員帳號管理
      <% end %>
      <%= link_to account_levels_path, class: "item" do %>
        <i class="child icon"></i>等級管理
      <% end %>
      <%= link_to messages_path, class: "item" do %>
        <i class="talk icon"></i>問答管理
      <% end %>
        </div>
        </div>
<%= link_to newsletters_path, class: "item" do %>
      <i class="in cart icon"></i>發送電子報
    <% end %>
      
    

    <div class="right menu">
      <div id="user_profile" class="ui icon dropdown blue item" style="color:#1678c2;">
        <i class="user icon"></i>
        管理者
      </div>
      <div id="profile_menu" class="ui popup transition hidden">
        <div class="ui secondary vertical icon menu">
          <%= link_to edit_account_path(@current_user), class: 'item' do %>
            <i class="primary-blue edit icon"></i>編輯帳號
          <% end %>
      
            <%= link_to orders_path, class: 'item' do %>
              <i class="primary-orange street view icon"></i>訂單管理
            <% end %>
        </div>
      </div>

      <%= link_to logout_consoles_path, class: "item", style: "color:#f2711c;" do %>
        <i class="sign out icon"></i>登出
      <% end %>
    </div>
    </div>
<% else %>
<div id="top_nav" class="ui top fixed large labeled icon menu grid" style="padding: 0 10px 0 10px;">
 <div class="grid menu row">
    <%= link_to consoles_path, class: "item" do %>
      <i class="home icon"></i>首頁
    <% end %>
    <%= link_to aboutus_consoles_path, class: "item" do %>
      <i class="in cart icon"></i>關於我們
    <% end %>

   <%= link_to newsboards_path, class: "item" do %>
      <i class="list layout icon"></i>最新消息

    <%= link_to products_path, class: "item" do %>
      <i class="calculator icon"></i>商品列表
    <% end %>
    <% if @current_user.present? %>
    <a class="inline item" href="/products/shoppingcart" data-html="<%if @barcarts.size>0 %>
    您的購物車商品列表<br>
    <div class='divider'></div>
    <table class='striped table'>
    <%@cartprice=0%>
    <%@barcarts.each do |b| %>
    <tr>
    <tr>
    <td class='graybg'>
    <img class='ui centered mini image' src='<%= asset_path '100px.png' %>' style='height: 40px; width: 40px; object-fit: contain'>
    </td>
    </tr>
    <td>
    <tr class='graybg'>
    <%=b.product.name%>
    </tr>
    <tr class='graybg'>數量：<%=b.sum %></tr>
    <tr class='graybg'>價格：<%=b.product_options.price*b.sum%>
    <%@cartprice += b.product_options.price*b.sum%>
    </tr>
    </td></tr><br>
    <%end%>
    </table>
    <div class='divider'></div>
    總價：<%=@cartprice%>
    <%else%>購物車是空的<%end%>">
        <i class="shipping icon"></i>購物車
      </a>  
   <%end%>
      <%= link_to shopprocess_products_path, class: "item" do %>
        <i class="retweet icon"></i>購物流程
      <% end %>

      <%= link_to new_message_path, class: "item" do %>
        <i class="sticky note icon"></i>留言版
      <% end %>
    <div class="right menu">

      <div id="user_profile" class="ui icon dropdown blue item" style="color:#1678c2;">
      <% if session[:profile_photo] != nil %>
      <img class='ui centered mini image' src='<%= session[:profile_photo] %>' style='height: 40px; width: 40px; object-fit: contain'>
      <%else%>
        <i class="user icon"></i>
        <%end%>
        <% if @current_user != nil %>

        <%= @current_user.name %>
        </div>
        <div id="profile_menu" class="ui popup transition hidden">
        <div class="ui secondary vertical icon menu">
          <%= link_to edit_account_path(@current_user), class: 'item' do %>
            <i class="primary-blue edit icon"></i>編輯帳號
          <% end %>
      
            <%= link_to orders_path, class: 'item' do %>
              <i class="primary-blue sticky note outline icon"></i></br>我的訂單
            <% end %>
            <%= link_to messages_path, class: 'item' do %>
              <i class="primary-blue talk outline icon"></i></br>我的留言
            <% end %>
            
         </div>
      </div>
        <% else %>
        未登入
        </div>
        <% end %>
      
              <% if @current_user != nil %>
      <%= link_to logout_consoles_path, style: "color:red;",class: "item" do %>
        <i class="sign out icon"></i>登出
      <% end %>
        <% else %>
      <a href="/consoles/login" class="item" style="color:#f2711c;">
        <i class="sign in icon"></i>
        登入
      </a>
        <% end %>
    </div>
    <%end%>
    </div>
<% end %>
<div class="ui small modal login" style="padding-top:0px;">
  <i class="close icon"></i>
  <div id="loginpage" style="padding:10px;">
  </div>
</div>
 <script type="text/javascript">
 $('.inline.item')
  .popup({
    inline: true
  })
;

$(function(){

  $("#login").click(function(){
    $("#login").addClass("loading");
    $.get( "/consoles/login", function(html) {
      $("#loginpage").empty();
      $("#loginpage").append(html);
      $("#login").removeClass("loading");

      $('.ui.modal.login').modal({
        observeChanges: true
      }).modal('refresh').modal('show');

    }).fail(function() {
      $("#login").removeClass("loading");
      alert( "error" );
    });

  });



});

// </script>

app/views/common/_topbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="topNav">
		<div class="container">
			<div class="alignR">
				<a class="active" href="/"> <i class="home icon"></i> 首頁</a> 
				
				
	<% if @current_user.present? && @current_user.role!=1%>
    <a class="inline item" href="/products/shoppingcart" data-html="<%if @barcarts.size>0 %>
    您的購物車商品列表<br>
    <div class='divider'></div>
    <table class='striped table'>
    <%@cartprice=0%>
    <%@barcarts.each do |b| %>
    <tr>
    <tr>
    <td class='graybg'>
    <img class='ui centered mini image' src='<%= asset_path '100px.png' %>' style='height: 40px; width: 40px; object-fit: contain'>
    </td>
    </tr>
    <td>
    <tr class='graybg'>
    <%=b.product.name%>
    </tr>
    <tr class='graybg'>數量：<%=b.sum %></tr>
    <tr class='graybg'>價格：<%=b.product_option.price*b.sum%>
    <%@cartprice += b.product_option.price*b.sum%>
    </tr>
    </td></tr><br>
    <%end%>
    </table>
    <div class='divider'></div>
    總價：<%=@cartprice%>
    <%else%>購物車是空的<%end%>">
        <a href="/products/shoppingcart"><i class="shipping icon"></i>購物車<span class="badge badge-warning"><%if @catrprice.present? %>$<%=@cartprice%><%end%></span></a>
      </a>
      <%end%>
      <% if @current_user.present? %>
      <% if @current_user.role==1 %>
      <a href="/accounts/myaccount"><i class="user icon"></i>管理員介面</a> 
      <%else%>
      <a href="/accounts/myaccount"><i class="user icon"></i><%= @current_user.name %></a> 
      <%end%>
      <a href="/consoles/logout"><i class="user icon"></i>登出</a> 
      <% else %>
      <a href="/consoles/login"><i class="user icon"></i>登入</a> 
      <% end %>
   
			</div>
		</div>
	</div>
</div>